_radio() 
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    if [[ ${cur} == -* ]] ; then
        opts="-infos -list -stop -web"
        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
        return 0
    else
        opts=$(radio -list)
        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
        return 0
    fi
}

complete -F _radio radio
